[package]
name = "unifrac"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
itertools = "0.13.0"
ndarray = "0.16.1"
phylotree = { git = "https://github.com/lucblassel/phylotree-rs" }
